export type UiLocale = "ar" | "en";

export function normalizeUiLocale(locale?: string | null): UiLocale {
  if (!locale) return "ar";
  return locale.toLowerCase().startsWith("en") ? "en" : "ar";
}

export const uiCopy = {
  ar: {
    appName: "ورق حر",
    login: "الدخول",
    register: "إنشاء حساب",
    compose: "إنشاء منشور",
    bottomNavLabel: "التنقل السفلي",
    home: "الرئيسية",
    media: "الميديا",
    messages: "الرسائل",
    search: "البحث",
    profile: "الملف الشخصي",
    dashboard: "لوحة المستخدم",
    activity: "النشاط",
    notifications: "الإشعارات",
    accountSettings: "إعدادات الحساب",
    security: "الأمان",
    settings: "الإعدادات",
    publicProfile: "الملف العام",
    followers: "متابعون",
    following: "يتابع",
    smartSort: "الترتيب الذكي",
    latestSort: "الأحدث أولًا",
    homeTitle: "الرئيسية",
    timelineTitle: "التايملاين",
    homeEyebrow: "ورق حر",
    timelineEyebrow: "التايم لاين",
    homeDescription:
      "تعرض الصفحة الرئيسية التايملاين مباشرة بتحميل أولي أخف، ثم يتم جلب المزيد أثناء السحب لأسفل.",
    timelineDescription:
      "يعرض التايملاين المنشورات بتحميل أولي أخف، ثم يواصل الجلب تلقائيًا أثناء السحب لأسفل.",
    quickSummary: "ملخص سريع",
    homeQuickSummary:
      "أصبحت الصفحة الرئيسية هي نقطة القراءة الأساسية، مع منشورات أقل في البداية ثم تحميل تلقائي مستمر.",
    timelineQuickSummary:
      "يبدأ التايملاين بعدد أقل من العناصر ليكون أسرع، ثم يواصل الجلب تلقائيًا أثناء السحب لأسفل.",
    myActivity: "نشاطي",
    mediaTitle: "الوسائط",
    mediaEyebrow: "Media",
    mediaDescription:
      "هذه الصفحة تعرض المنشورات التي تحتوي على صور أو روابط وسائط بشكل مباشر.",
    mediaSummary: "ملخص الوسائط",
    mediaSummaryText: "يوجد الآن {count} منشورًا يحتوي على وسائط متاحة للعرض.",
    openPost: "فتح المنشور",
    postAuthor: "صاحب المنشور",
    noMediaTitle: "لا توجد وسائط بعد",
    noMediaDescription: "عندما تتوفر منشورات تحتوي على صور أو وسائط ستظهر هنا.",
    messagesTitle: "الرسائل الخاصة",
    messagesEyebrow: "Messages",
    messagesDescription: "هنا تجد محادثاتك الخاصة مرتبة من الأحدث إلى الأقدم.",
    messagesSummary: "ملخص الرسائل",
    messagesSummaryText: "لديك الآن {unread} رسالة غير مقروءة عبر {count} محادثة.",
    openConversation: "فتح المحادثة",
    backToMessages: "العودة إلى الرسائل",
    openPublicProfile: "فتح الملف العام",
    noConversationsTitle: "لا توجد محادثات بعد",
    noConversationsDescription: "عندما تبدأ محادثات خاصة بين المستخدمين ستظهر هنا.",
    lastMessage: "آخر رسالة",
    noMessagesYet: "لا توجد رسائل بعد",
    sentStatus: "تم الإرسال",
    readStatus: "تمت القراءة",
    searchTitle: "البحث",
    searchEyebrow: "Search",
    searchDescription: "ابحث عن حسابات أو كلمات أو منشورات من مكان واحد.",
    searchPlaceholder: "ابحث عن حساب أو كلمة أو منشور",
    searchButton: "بحث",
    clearButton: "مسح",
    startSearch: "ابدأ البحث",
    startSearchDescription: "اكتب اسم مستخدم أو كلمة أو عنوان منشور لعرض النتائج هنا.",
    usersSection: "الحسابات",
    postsSection: "المنشورات",
    noUsersTitle: "لا توجد حسابات",
    noUsersDescription: "لم يتم العثور على حسابات مطابقة.",
    noPostsTitle: "لا توجد منشورات",
    noPostsDescription: "لم يتم العثور على منشورات مطابقة.",
    viewProfile: "عرض الملف",
    privateMessage: "مراسلة خاصة",
    followersCountLabel: "{count} متابعون",
    followingCountLabel: "{count} يتابع",
    quickActions: "اختصارات سريعة",
    quickActionsDescription:
      "انتقل مباشرة إلى أهم المسارات المرتبطة بحسابك وتجربتك الاجتماعية.",
    myPublicProfile: "ملفي العام",
    myMessages: "رسائلي",
    mySettings: "إعداداتي",
    openDashboard: "لوحة المستخدم",
  },
  en: {
    appName: "Waraqhur",
    login: "Login",
    register: "Register",
    compose: "Compose Post",
    bottomNavLabel: "Bottom navigation",
    home: "Home",
    media: "Media",
    messages: "Messages",
    search: "Search",
    profile: "Profile",
    dashboard: "Dashboard",
    activity: "Activity",
    notifications: "Notifications",
    accountSettings: "Account Settings",
    security: "Security",
    settings: "Settings",
    publicProfile: "Public Profile",
    followers: "Followers",
    following: "Following",
    smartSort: "Smart ranking",
    latestSort: "Latest first",
    homeTitle: "Home",
    timelineTitle: "Timeline",
    homeEyebrow: "Waraqhur",
    timelineEyebrow: "Timeline",
    homeDescription:
      "The home page now opens directly into the timeline with a lighter initial load, then fetches more posts automatically while scrolling.",
    timelineDescription:
      "The timeline starts with a lighter initial load, then continues fetching more posts automatically while scrolling.",
    quickSummary: "Quick Summary",
    homeQuickSummary:
      "The home page is now the main reading surface, with fewer posts at first and continuous automatic loading afterward.",
    timelineQuickSummary:
      "The timeline starts with fewer items for a faster load, then keeps fetching more posts automatically while scrolling.",
    myActivity: "My Activity",
    mediaTitle: "Media",
    mediaEyebrow: "Media",
    mediaDescription:
      "This page shows posts that contain images or media links directly.",
    mediaSummary: "Media Summary",
    mediaSummaryText: "There are now {count} posts with media available to browse.",
    openPost: "Open Post",
    postAuthor: "Post Author",
    noMediaTitle: "No media yet",
    noMediaDescription: "Posts with images or media will appear here when available.",
    messagesTitle: "Private Messages",
    messagesEyebrow: "Messages",
    messagesDescription: "Here you can find your private conversations ordered from newest to oldest.",
    messagesSummary: "Messages Summary",
    messagesSummaryText: "You currently have {unread} unread messages across {count} conversations.",
    openConversation: "Open Conversation",
    backToMessages: "Back to Messages",
    openPublicProfile: "Open Public Profile",
    noConversationsTitle: "No conversations yet",
    noConversationsDescription: "Private conversations will appear here when users start messaging.",
    lastMessage: "Last Message",
    noMessagesYet: "No messages yet",
    sentStatus: "Sent",
    readStatus: "Read",
    searchTitle: "Search",
    searchEyebrow: "Search",
    searchDescription: "Search for users, keywords, or posts from one place.",
    searchPlaceholder: "Search for a user, keyword, or post",
    searchButton: "Search",
    clearButton: "Clear",
    startSearch: "Start Searching",
    startSearchDescription: "Enter a username, keyword, or post title to show results here.",
    usersSection: "Users",
    postsSection: "Posts",
    noUsersTitle: "No users found",
    noUsersDescription: "No matching user accounts were found.",
    noPostsTitle: "No posts found",
    noPostsDescription: "No matching posts were found.",
    viewProfile: "View Profile",
    privateMessage: "Private Message",
    followersCountLabel: "{count} followers",
    followingCountLabel: "{count} following",
    quickActions: "Quick Actions",
    quickActionsDescription:
      "Jump directly to the most important parts of your account and social experience.",
    myPublicProfile: "My Public Profile",
    myMessages: "My Messages",
    mySettings: "My Settings",
    openDashboard: "Open Dashboard",
  },
} as const;
